export const CATEGORIES = {
  GET_CATEGORIES: 'GET_CATEGORIES',
}

export const PRODUCTS = {
  GET_PROD_BY_CAT: 'GET_PROD_BY_CAT',
}

export const CART = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
}

export const VENDORS = {
  GET_VENDORS: 'GET_VENDORS',
}

export const HOME = {
  GET_HOME_CONTENT: 'GET_HOME_CONTENT',
  GET_HOME_SINGLE_PRODUCT: 'GET_HOME_SINGLE_PRODUCT',
}
